version: 2

jobs:

  build:
    working_directory: ~/repo
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker container
          command: docker build -t mrp4p3r/recrierbot .
      - run:
          name: docker save image
          command: |
            mkdir -p ~/images/ || true
            docker save -o ~/images/mrp4p3r.recrierbot.tar mrp4p3r/recrierbot
      - save_cache:
          key: image-recrierbot-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/images

  docker-push:
    docker:
      - image: docker:18
    steps:
      - restore_cache:
          key: image-recrierbot-{{ .Environment.CIRCLE_SHA1 }}
      - setup_remote_docker
      - run:
          name: Restore recrierbot image
          command: |
            docker load -i ~/images/mrp4p3r.recrierbot.tar
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker push mrp4p3r/recrierbot
            fi

workflows:

  version: 2

  build-and-push:
    jobs:
      - build
      - docker-push:
          requires:
            - build
          filters:
            branches:
              only: master
