version: 2
jobs:
  build:
    working_directory: /repo
    docker:
      - image: docker:18
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build alpine bot server binary
          command: |
            docker run -d --entrypoint sh --name botserver-builder mrp4p3r/pyinstaller-alpine-py3 -c 'sleep 1h'
            docker cp /repo/. botserver-builder:/src
            docker exec botserver-builder /pyinstaller/pyinstaller.sh \
                --noconfirm --log-level DEBUG --distpath /src/dist-alpine main.py
            mkdir -p /repo/dist-alpine
            docker cp botserver-builder:/src/dist-alpine/main /repo/dist-alpine
      - run:
          name: Build Docker image for bot
          command: docker build -t mrp4p3r/recrierbot .
      - deploy:
          name: Push Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}"
              docker push mrp4p3r/recrierbot
            fi
